routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();


//reset pass
Route::post('/password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/reset','Auth\ResetPasswordController@reset');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');

Route::prefix('base')->group(function () {
    Route::get('/home', 'BaseApp\HomeController@index')->name('base.home');
    Route::get('/home/page', 'BaseApp\HomeController@loadpage')->name('base.page');
    /**
     * Login base
     */
    Route::get('/login','Auth\LoginController@showLoginForm')->name('base.login');
    Route::post('/login','Auth\LoginController@login');
    Route::post('/logout','Auth\LoginController@logout')->name('base.logout');
    /**
     * Route User
     */
    Route::resource('users','BaseApp\UserController');
    Route::get('profile','BaseApp\ProfileController@index')->name('base.profile');
    Route::patch('profile','BaseApp\ProfileController@update')->name('base.updateprofile');
    /**
     * Route Portals
     */
    Route::resource('portals','BaseApp\PortalController');
    /**
     * Route Roles
     */
    Route::resource('roles','BaseApp\RoleController');
    /**
     * Route Navigation
     */
    Route::resource('navs','BaseApp\NavController',  ['except' => ['create', 'edit']]);
    Route::get('/navs/view/{portal_id}', 'BaseApp\NavController@view')->name('navs.view');
    Route::get('/navs/create/{portal_id}', 'BaseApp\NavController@create')->name('navs.create');
    Route::get('/navs/{portal_id}/{nav}/edit', 'BaseApp\NavController@edit')->name('navs.edit');
    /**
     * Route Permissions
     */
    Route::get('/permissions','BaseApp\PermissionController@index')->name('permissions.index');
    Route::get('/permissions/{role}','BaseApp\PermissionController@edit')->name('permissions.edit');
    Route::post('/permissions/{role}','BaseApp\PermissionController@update')->name('permissions.update');
    Route::get('/forbidden/page/{code}/{nav_id?}','BaseApp\ForbiddenAccess@page')->name('baseapp.forbidden');
    /**
     * Route Preferences
     */
    Route::resource('/preferences','BaseApp\PreferenceController');

});

app/Http/Controllers/BaseApp/ForbiddenAccess.php
<?php

namespace App\Http\Controllers\BaseApp;

use App\Http\Controllers\Base\BaseAdminController;
use App\Repositories\BaseApp\NavRepositories;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ForbiddenAccess extends BaseAdminController
{
    public function __construct(Request $request)
    {
        // load parent construct
        parent::__construct($request);
    }

    // forbidden page
    public function page($code, $nav_id = '') {
        // set page template
        $this->setTemplate('errors.BaseApp.error_page');
        // get navigation info
        if (!empty($nav_id)) {
            $result = NavRepositories::getById($nav_id)->toArray();
        }
        switch ($code) {
            case 403 :
                $data = [
                    'code' => $code,
                    'message' => '<b>Maaf,</b> anda tidak mempunyai akses penuh ke halaman <b>'.Str::lower($result['nav_title']).'</b>.'
                ];
                break;
            case 404:
                $data = [
                    'code' => $code,
                    'message' => '<b>Maaf,</b> Halaman yang anda request tidak tersedia'
                ];
                break;
        }
        $this->assign("data", $data);
        // output
        return  $this->displayPage();
    }
}

app/Http/Controllers/BaseApp/HomeController.php
<?php

namespace App\Http\Controllers\BaseApp;

use App\Http\Controllers\Base\BaseAdminController;
use App\Libs\LogLib\LogRepository;
use App\Repositories\BaseApp\NavRepositories;
use App\Repositories\BaseApp\PortalRepositories;
use App\Repositories\BaseApp\RoleRepositories;
use App\Repositories\BaseApp\UserRepositories;
use Illuminate\Http\Request;

class HomeController extends BaseAdminController
{
    /**
     * Create a new controller instance.
     *
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        parent::__construct($request);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->setRule('r');
        // set page template
        $this->setTemplate('BaseApp.admin.home');
        // set page header
        $this->setPageHeaderTitle('<span class="text-semibold">Home</span> - Dashboard');
        // load js
        $this->loadJs('theme/admin-template/js/plugins/notifications/sweet_alert.min.js');
        $this->loadJs('theme/admin-template/js/plugins/buttons/spin.min.js');
        $this->loadJs('theme/admin-template/js/plugins/buttons/ladda.min.js');
        $this->loadJs('js/BaseApp/home/page_home.js');
        // set breadcumb
        $data = [
            [
                'icon' => 'icon-home2',
                'title' => 'Dasboard'
            ],
        ];
        $userRepositories = new UserRepositories();
        $roleRepositories = new RoleRepositories();
        $portalRepositories = new PortalRepositories();
        $navRepositories = new NavRepositories();
        $this->assign('countUser', $userRepositories->getCountUser());
        $this->assign('countRole', $roleRepositories->getCountRole());
        $this->assign('countPortal', $portalRepositories->getCountPortal());
        $this->assign('countNav', $navRepositories->getCountNav());
        $this->assign('logs', LogRepository::getLogPortal(1, 10));
        $this->setBreadcumb($data);
        return $this->displayPage();
    }

    public function loadpage(Request $request)
    {
        // cek apakah ajax request
        if ($request->ajax()){
            // cek rule
            $access = $this->setRule('r');
            if($access['access'] == 'failed'){
                return response(['message' => $access['message'], 'status' => 'failed']);
            }
            $htmlData = '';
            $data = LogRepository::getLogPortal(1, 10);

            // default response
            foreach ($data as $log) {
                $htmlData .= '<div class="timeline-row"><div class="timeline-icon"><a href="#">';
                $htmlData .= '<img alt="log" class="img-circle" src="http://localhost:8000/theme/admin-template/images/placeholder.jpg">';
                $htmlData .= '</a></div><div class="row"><div class="col-lg-12"><div class="panel panel-flat timeline-content"><div class="panel-heading">';
                $htmlData .= '<h6 class="panel-title">' . $log->user->name . '<a class="heading-elements-toggle"><i class="icon-more"></i></a></h6>';
                $htmlData .= '<div class="heading-elements"><span class="heading-text"><i class="icon-checkmark-circle position-left text-success"></i>' . $log->created_at->diffForHumans() . '</span><ul class="icons-list"></ul></div></div>';
                $htmlData .= '<div class="panel-body"><h6 class="content-group"><i class="icon-user-check position-left"></i><a href="#"></a>' . $log->action . ' :</h6>';
                $htmlData .= '<blockquote><p>' . $log->description . '</p><footer>' . $log->user->username . ', <cite title="Source Title">' . $log->created_at->format('h:i A') . '</cite></footer></blockquote>';
                $htmlData .= '</div></div></div></div></div>';
            }
            if(is_null($data->nextPageUrl())){
                return response(['logs' => $htmlData,'end' => true]);
            }else{
                return response(['logs' => $htmlData,'end' => false]);
            }
        }
        // default response
        return response(['message' => 'Gagal mengambil data', 'status' => 'failed']);

    }
}

app/Http/Controllers/BaseApp/PermissionController.php
<?php

namespace App\Http\Controllers\BaseApp;

use App\Http\Controllers\Base\BaseAdminController;

use App\Repositories\BaseApp\PermissionRepositories;
use App\Repositories\BaseApp\RoleRepositories;
use App\Model\Role;
use Illuminate\Http\Request;

class PermissionController extends BaseAdminController
{
    /**
     * @var PermissionRepositories
     */
    private $permissionRepositories;

    /**
     * @var RoleRepositories
     */
    private $roleRepositories;

    public function __construct(PermissionRepositories $permissionRepositories, Request $request, RoleRepositories $roleRepositories)
    {
        parent::__construct($request);
        $this->permissionRepositories = $permissionRepositories;
        $this->roleRepositories = $roleRepositories;
    }

    public function index()
    {
        // set rule page
        $this->setRule('r');
        // set page template
        $this->setTemplate('BaseApp.permissions.index');
        //set page title
        $this->setPageHeaderTitle('<span class="text-semibold">Permissions</span> - List Role');
        // set breadcumb
        $data = [
            [
                'icon' => 'icon-user-lock',
                'url' => 'home',
                'title' => 'Dasboard'
            ],
            [
                'title' => 'List Role Permissions'
            ]
        ];
        $this->setBreadcumb($data);
        //assign data
        $this->assign('roles', $this->roleRepositories->getListPaginate(10));
        // display page
        return $this->displayPage();
    }

    public function edit(Role $role)
    {
        // set rule page
        $this->setRule('u');
        // set page template
        $this->setTemplate('BaseApp.permissions.edit');
        // load js
        $this->loadJs('theme/admin-template/js/plugins/forms/styling/uniform.min.js');
        //set page title
        $this->setPageHeaderTitle('<span class="text-semibold">Permissions</span> - List Menu');
        // set breadcumb
        $data = [
            [
                'icon' => 'icon-user-lock',
                'url' => 'home',
                'title' => 'Dasboard'
            ],
            [
                'url' => 'permissions',
                'title' => 'List Role'
            ],
            [
                'title' => 'List Menu'
            ]
        ];
        $this->setBreadcumb($data);
        // get data
        $listMenu  = $this->permissionRepositories->getListMenu($role->portal_id,0,'');
        foreach ( $listMenu as $key => $menu) {
            $c = isset($menu->roles->where('id','=',$role->id)->first()->pivot->c) ?  $menu->roles->where('id','=',$role->id)->first()->pivot->c :  0;
            $r = isset($menu->roles->where('id','=',$role->id)->first()->pivot->r) ?  $menu->roles->where('id','=',$role->id)->first()->pivot->r :  0;
            $u = isset($menu->roles->where('id','=',$role->id)->first()->pivot->u) ?  $menu->roles->where('id','=',$role->id)->first()->pivot->u :  0;
            $d = isset($menu->roles->where('id','=',$role->id)->first()->pivot->d) ?  $menu->roles->where('id','=',$role->id)->first()->pivot->d :  0;
            if($c == 1 && $r == 1 && $u == 1 && $d == 1){
                $listMenu[$key]->check_all = true;
            }else{
                $listMenu[$key]->check_all = false;
            }
        }
        //assign data
        $this->assign('role', $role);
        $this->assign('listMenu', $listMenu );
        // display page
        return $this->displayPage();
    }

    public function update(Role $role, Request $request)
    {
        // set rule page
        $this->setRule('u');
        // proses update permissions
        $this->permissionRepositories->update($request->all(),$role);
        flash('Berhasil mengupdate permissions.')->success()->important();
        // redirect page
        return redirect('base/permissions/'.$role->id);
    }
}

app/Http/Controllers/BaseApp/ProfileController.php
<?php

namespace App\Http\Controllers\BaseApp;

use App\Http\Controllers\Base\BaseAdminController;
use App\Http\Requests\BaseApp\UserRequest;
use App\Repositories\BaseApp\UserRepositories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfileController extends BaseAdminController
{

    /**
     * @var UserRepositories
     */
    protected $repositories;

    /**
     * UserController constructor.
     * @param UserRepositories $repositories
     * @param Request $request
     * @internal param Users $users
     */
    public function __construct(UserRepositories $repositories, Request $request)
    {
        // load parent construct
        parent::__construct($request);
        $this->repositories = $repositories;
    }

    /**
     * Show form edit data user login
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function index()
    {
        // set rule page
        $this->setRule('r');
        // set page template
        $this->setTemplate('BaseApp.users.profile');
        // load js
        $this->loadJs('theme/admin-template/js/plugins/forms/inputs/passy.js');
        $this->loadJs('js/BaseApp/plugin/initialPassy.js');
        $this->loadJs('theme/admin-template/js/plugins/forms/validation/validate.min.js');
        $this->loadJs('theme/admin-template/js/plugins/forms/validation/additional_methods.min.js');
        $this->loadJs('theme/admin-template/js/plugins/forms/selects/select2.min.js');
        $this->loadJs('js/BaseApp/user/page_user.js');
        $this->loadJs('js/BaseApp/user/validation-edit.js');
        //set page title
        $this->setPageHeaderTitle('<span class="text-semibold">Users</span> - Profile User');
        // set breadcumb
        $data = [
            [
                'icon' => 'icon-users',
                'url' => 'home',
                'title' => 'Dasboard'
            ],
            [
                'title' => 'Profil User'
            ]
        ];
        $this->setBreadcumb($data);
        //assign data
        $this->assign('user', Auth::user());
        return $this->displayPage();
    }

    /**
     * Update the user login data.
     * @param UserRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(UserRequest $request)
    {
        // set rule page
        $this->setRule('u');
        // proses update data user di database
        if($this->repositories->updateUserLogin($request->all())){
            // set notification success
            flash('Berhasil ubah data user')->success()->important();
        }else{
            // set notification error
            flash('Gagal ubah data user')->error()->important();
        }
        // redirect page
        return redirect('base/profile');
    }
}

resources/views/Baseapp/users/add.blade.php
@extends('layouts.admin.app')

@section('page-header')
    @include('layouts.admin.page-header')
@stop
@section('content')
    <!-- Input group addons -->
    <div class="panel  panel-white">
        <div class="panel-heading">
            <h5 class="panel-title">Form Add User</h5>
            <div class="heading-elements">
                <a href="{{ route('users.index') }}" class="btn btn-xs border-slate text-slate-800 btn-flat btn-rounded">
                    <i class="icon-arrow-left7 position-left"></i> Kembali
                </a>
            </div>
        </div>
        {!! Form::model($article = new \App\Model\User(),['url' => 'base/users'], ['class' => 'form-horizontal form-validate-user']) !!}
            @include('Baseapp.users.form',['textButton' => 'Add', 'icon' => 'icon-plus3'])
        {!! Form::close() !!}
    </div>
    <!-- /input group addons -->
@endsection

resources/views/Baseapp/users/edit.blade.php
@extends('layouts.admin.app')

@section('page-header')
@include('layouts.admin.page-header')
@stop
@section('content')
        <!-- Input group addons -->
<div class="panel  panel-white">
    <div class="panel-heading">
        <h5 class="panel-title">Form Edit User</h5>
        <div class="heading-elements">
            <a href="{{ route('users.index') }}" class="btn btn-xs border-slate text-slate-800 btn-flat btn-rounded">
              <i class="icon-arrow-left7 position-left"></i> Kembali
            </a>
        </div>
    </div>
    {!! Form::model($user ,['method' => 'PATCh','action' => ['BaseApp\UserController@update', $user->id]], ['class' => 'form-horizontal form-validate-user-edit']) !!}
        @include('Baseapp.users.form',['textButton' => 'Edit', 'icon' => 'icon-pencil5'])
    {!! Form::close() !!}
</div>
<!-- /input group addons -->
@endsection

resources/views/Baseapp/users/form.blade.php
<div class="panel-body">
    {{--include notification--}}
    @include('flash::message')
    {{--end include notification--}}
    <div class="form-group">
        {!! Form::label('name','Name ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            {!! Form::text('name',null,['class' => 'form-control ' , 'placeholder' => 'Name','required' =>'required']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('username','Username ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            {!! Form::text('username',null,['class' => 'form-control ','placeholder' => 'Username','required' =>'required']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('email','Email ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            {!! Form::email('email',null,['class' => 'form-control ','placeholder' => 'Email','required' =>'required']) !!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('role_id','Role ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            {!! Form::select('role_id',$roles, null,['id' => 'role_id','class' => 'form-control '])!!}
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('password','Password ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            <div class="label-indicator-absolute">
                {!! Form::password('password',['class' => 'form-control ','placeholder' => 'Password']) !!}
                <span class="label password-indicator-label-absolute"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        {!! Form::label('password_confirm','Confirmasion Password ',['class' => 'control-label col-lg-2']) !!}
        <div class="col-lg-10">
            {!! Form::password('password_confirm',['class' => 'form-control ','placeholder' => 'Confirmasion Password']) !!}
        </div>
    </div>
</div>
<div class="panel-footer">
    <div class="text-right">
        <button type="submit" class="btn bg-teal-400 pull-right fix-width btn-md m-right-20" >
            <i class="{{$icon}}"></i>&nbsp;&nbsp;{{$textButton}}
        </button>
        <button type="reset" class="btn btn-default pull-right fix-width btn-md m-right-10" id="reset">
            <i class="icon-reload-alt position-right"></i> Reset
        </button>
    </div>
</div>
@section('costum-js')
    <script>
        $('#role_id').select2({
            placeholder : 'pilih role'
        });
    </script>
@stop

resources/views/Baseapp/users/index.blade.php
@extends('layouts.admin.app')

@section('page-header')
    @include('layouts.admin.page-header')
@stop
@section('content')
    <!-- Simple lists -->
    <div class="row">
        <div class="col-md-12">
            <!-- Table header styling -->
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Table List User</h5>
                    <div class="heading-elements">
                        <a href="{{ route('users.create') }}" class="btn btn-xs border-slate text-slate-800 btn-flat btn-rounded">
                            Tambah User
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    {{--include notification--}}
                    @include('flash::message')
                    {{--end include notification--}}
                    <div class="table-responsive col-sm-12" style="padding: 0.5px !important;">
                        <table class="table">
                            <thead>
                            <tr class="bg-teal-400">
                                <th>#</th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody class="table-bordered">
                            @forelse($users as $key => $user)
                            <tr>
                                <td>{{ (($users->currentPage() - 1 ) * $users->perPage() ) + ($key+1) }}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->username}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->role->role_nm}}</td>
                                <td>
                                    <ul class="icons-list">
                                        <li class="text-primary-600"><a href="{{ route('users.edit',$user->id) }}"><i class="icon-pencil7"></i></a></li>
                                        <li class="text-danger-600"><a href="#" class="delete-user" data-id="{{$user->id}}" data-url ="{{ route('users.destroy',$user->id) }}" data-token="{{ csrf_token() }}"><i class="icon-trash"></i></a></li>
                                    </ul>
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td colspan="6">
                                        <div class="alert alert-info alert-bordered">
                                            <span class="text-semibold">Info !</span> Data tidak ditemukan.
                                        </div>
                                    </td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 col-xs-12 m-top-20">
                            <div class="pull-left">
                                @if ($users->hasPages())
                                <p>
                                    Halaman {{ $users->currentPage() }} dari {{ $users->total() }} Halaman
                                </p>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-6 col-xs-12 m-top-20">
                            <div class="pull-right">
                                {{--generate pagination--}}
                                {{ $users->links()}}
                                {{-- end generate pagination--}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /table header styling -->

        </div>
    </div>
    <!-- /simple lists -->
@endsection

resources/views/Baseapp/users/profile.blade.php
@extends('layouts.admin.app')

@section('page-header')
@include('layouts.admin.page-header')
@stop
@section('content')
        <!-- Input group addons -->
<div class="panel  panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Form Edit Profile</h5>
        <div class="heading-elements">
        </div>
    </div>
    {!! Form::model($user ,['method' => 'PATCH', 'action' => ['BaseApp\ProfileController@update']], ['class' => 'form-horizontal form-validate-user-edit']) !!}
    <div class="panel-body">
        {{--include notification--}}
        @include('flash::message')
        {{--end include notification--}}
        <div class="form-group">
            {!! Form::label('name','Name ',['class' => 'control-label col-lg-2']) !!}
            <div class="col-lg-10">
                {!! Form::text('name',null,['class' => 'form-control ' , 'placeholder' => 'Name','required' =>'required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('username','Username ',['class' => 'control-label col-lg-2']) !!}
            <div class="col-lg-10">
                {!! Form::text('username',null,['class' => 'form-control ','placeholder' => 'Username','required' =>'required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('email','Email ',['class' => 'control-label col-lg-2']) !!}
            <div class="col-lg-10">
                {!! Form::email('email',null,['class' => 'form-control ','placeholder' => 'Email','required' =>'required']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('password','Password ',['class' => 'control-label col-lg-2']) !!}
            <div class="col-lg-10">
                <div class="label-indicator-absolute">
                    {!! Form::password('password',['class' => 'form-control ','placeholder' => 'Password']) !!}
                    <span class="label password-indicator-label-absolute"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('password_confirm','Confirmasion Password ',['class' => 'control-label col-lg-2']) !!}
            <div class="col-lg-10">
                {!! Form::password('password_confirm',['class' => 'form-control ','placeholder' => 'Confirmasion Password']) !!}
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-right">
            <button type="submit" class="btn bg-teal-400 pull-right fix-width btn-md m-right-20" >
                <i class="icon-pencil5"></i>&nbsp;&nbsp;Edit
            </button>
            <button type="reset" class="btn btn-default pull-right fix-width btn-md m-right-10" id="reset">
                <i class="icon-reload-alt position-right"></i> Reset
            </button>
        </div>
    </div>
    {!! Form::close() !!}
</div>
<!-- /input group addons -->
@endsection